name: Vorpal Code Scan

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# name: vorpal-reviewdog
on:
  push:
    branches: [master]  # Adjust this to your default branch
  pull_request:
    branches: [master] 

jobs:
  vorpal:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Vorpal with reviewdog
        uses: checkmarx/vorpal-reviewdog-github-action@v1.0.0
        with:
          source_path: 'app/assets/js/chart/chart-data-morris.js,app/assets/js/tour/redirects-steps.js,app/data/allocations-dao.js,app/data/benefits-dao.js,app/data/contributions-dao.js,app/data/memos-dao.js,app/data/profile-dao.js,app/data/research-dao.js,app/data/user-dao.js,vulnerable_code/application.js,vulnerable_code/vulns.js'      # Adjust file patterns as needed
          filter_mode: file
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          fail_on_error: false

      - name: Display Vorpal Scan Results
        if: always()
        run: |
          echo "Vorpal Scan Results:"
          cat /github/workspace/result.errorformat || echo "No issues found."
